server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: hogu-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: |
        SET search_path TO hogu;
        SET TIME ZONE 'UTC';

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: hogu
        jdbc.time_zone: UTC

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX

springdoc:
  swagger-ui:
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 ora in millisecondi

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox

aws:
  ses:
    sender-email: ${AWS_SES_SENDER_EMAIL}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

stadia:
  api:
    key: ${STADIA_API_KEY}
    base-url: https://api.stadiamaps.com

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
